---
title: "p8105_hw2_sl4658"
author: "Simin Ling"
date: "9/30/2020"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
```


## Problem 1
Read and clean the Mr. Trash Wheel dataset.
```{r}
trashwheel_df = 
  read_excel("~/Desktop/Fall 2020/Data Science/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
            sheet = "Mr. Trash Wheel", 
            range = "A2:N408") %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(sports_balls = round(sports_balls),
         sports_balls = as.integer(sports_balls))
```

Read and clean precipitation data for 2017
```{r}
precip_2017_df = 
  read_excel("~/Desktop/Fall 2020/Data Science/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
            sheet = "2017 Precipitation", 
            range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(year = 2017)
```

Read and clean precipitation data for 2018
```{r}
precip_2018_df = 
  read_excel("~/Desktop/Fall 2020/Data Science/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
            sheet = "2018 Precipitation", 
            range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(year = 2018)
```

